### ISSUE TITLE
[Policy Violation] DMCA Alert - Code Reuse without Fork/Credits

### ISSUE THREAD

**Issue by pranjal-joshi** [SerendipityOrg/TradeMan#1]
Hi Team and @amolkittur @omkarh25 @Serendipity2-0 

It has been observed that this repository contains the code taken from my open-source [repository](https://github.com/pranjal-joshi/Screeni-py)
Even though the code is published along with an MIT license, in case of re-uploading my code on this repository requires you to mention the credits on your repo explicitly and referring to the source repo in your markdown file is also required.

This can be avoided by forking my repo on GitHub instead of re-uploading the code via performing a new commit.

Please mention the credits and refer back to [Screeni-py](https://github.com/pranjal-joshi/Screeni-py) in your markdown or else delete this repo and fork a new one from Screeni-py and make the changes as you want.

Looking forward for cooperation from your side ASAP otherwise, I may have to proceed further with a DMCA takedown notice as suggested by Github.

Thank you.

**Comment by omkarh25** [comment]
Hey Pranjal,
Sorry for reusing the code without mentioning the credits. The intention
was not to plagiarize but to assemble something quick to run a trading algo
(newbie coders here). I really admire and appreciate your work. Since the
project folder has few other implementations independent of screenipy, I'll
will mention credits in the markdown as you suggested.

Cheers,
Omkar

**Comment by Serendipity2-0** [comment]
Updated readme. Please do let me know if its appropriate

**Comment by pranjal-joshi** [comment]
Thanks for complying with the best practices for open source @Serendipity2-0 
👍
